### ISSUE TITLE
devshell doesn't work with flake version of nix-direnv 1.5.0

### ISSUE THREAD

**Issue by johnae** [numtide/devshell#149] opened 2021-11-16 20:06 UTC
**Describe the bug**

Nix-direnv 1.5.0 has stopped executing the shellHook when cached in the flake version of it since that mirrors how the classic nix version works (it doesn't execute the shellHook). Since, afaict, devshell depends on the shellHook executing even when cached this broke devshell on nix-direnv 1.5.0.

Personally I'm not entirely sure it is correct to stop executing the shellHook since, as the pull request that changes this behavior in nix-direnv notes, `nix develop` does in fact always execute the shellHook. So the bug might actually be in nix-direnv.

**To Reproduce**

Update nix-direnv to 1.5.0, then try entering a directory with a devshell in it that is already cached and you'll find that you don't have any of the expected executables in PATH.

**Expected behavior**

That devshell works together with nix-direnv 1.5.0

**System information**

nix-direnv 1.5.0 and devshell from master.

**Additional context**

This is a relevant issue in nix-direnv: https://github.com/nix-community/nix-direnv/issues/109

**Comment by zimbatm** [comment] 2021-11-17 21:31
I think the issue is on nix-direnv's side.

**Comment by charmoniumQ** [comment] 2022-05-09 19:17
Nix-direnv PR is merged; we can probably close this?

**Closed** 2022-05-11 16:35 UTC
Labels: bug
